steps:
- id: build-image
  name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/app:$SHORT_SHA', '.']
- id: push-image
  name: 'docker'
  args: ['push', 'gcr.io/$PROJECT_ID/app:$SHORT_SHA']
- id: deploy
  name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '$_SERVICE_NAME'
  - '--image'
  - 'gcr.io/$PROJECT_ID/app:$SHORT_SHA'
  - '--set-env-vars'
  - >- 
    ^;^
    GIN_MODE=$_GIN_MODE;
    LOG_LEVEL=$_LOG_LEVEL;
    TRACE_SAMPLE=$_TRACE_SAMPLE;
    PUBSUB_PROJECT=$_PUBSUB_PROJECT;
    PUBSUB_TOPIC=$_PUBSUB_TOPIC;
    PUBSUB_SUBSCRIPTION=$_PUBSUB_SUBSCRIPTION;
    BIGQUERY_PROJECT=$_BIGQUERY_PROJECT;
    BIGQUERY_DATASET=$_BIGQUERY_DATASET;
    BIGQUERY_TABLE=$_BIGQUERY_TABLE
  - '--no-allow-unauthenticated'
  - '--no-cpu-throttling'
  - '--min-instances'
  - '1'
  - '--max-instances'
  - '5'
  - '--project'
  - '$_PROJECT'
  - '--region'
  - '$_REGION'

